# Generated by Django 3.0.7 on 2020-07-10 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Human',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('surname', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('birth', models.DateField()),
                ('company', models.CharField(choices=[('itvdn', ' Itvdn'), ('yandex', ' Yandex'), ('epam', ' Epam'), ('google', ' Google')], max_length=150)),
                ('position', models.CharField(choices=[('senior', 'Senior'), ('middle', 'Middle'), ('junior', 'Junior')], max_length=15)),
                ('language', models.CharField(choices=[('javascript', 'javascript'), ('c#', 'C#'), ('cpp', 'C++'), ('python', 'python')], default='python', max_length=10)),
                ('salary', models.IntegerField()),
            ],
        ),
    ]
