# Generated by Django 3.0.7 on 2020-07-07 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Example',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('integer_field', models.IntegerField()),
                ('positive_field', models.PositiveIntegerField()),
                ('positive_small_field', models.PositiveSmallIntegerField()),
                ('big_integert_field', models.BigIntegerField()),
                ('float_field', models.FloatField()),
                ('binary_field', models.BinaryField()),
                ('boolean_field', models.BooleanField()),
                ('char_field', models.CharField(max_length=5)),
                ('text_field', models.TextField(max_length=20)),
                ('date_field', models.DateField(auto_now=True)),
                ('date_time_field', models.DateTimeField(auto_now_add=True)),
                ('decimal_field', models.DecimalField(decimal_places=2, max_digits=8)),
                ('email', models.EmailField(max_length=254)),
                ('file_field', models.FileField(upload_to='file')),
                ('image_field', models.ImageField(upload_to='images')),
            ],
        ),
    ]
